### ISSUE TITLE
ManagedArrayBlockingQueue permanently reduces throughput when session release throws

### ISSUE THREAD

**Issue by sirmax** [slick/slick#2430]
**DESCRIPTION:**

We use slick 3.3.3 with bounded `AsyncExecutor`, which uses `ManagedArrayBlockingQueue` under the hood. `ManagedArrayBlockingQueue` uses inner `inUseCount` to constrain the number of actions being sent for execution in parallel.

A few times during a DB failover `ManagedArrayBlockingQueue` in our application has failed to decrement `inUseCount`, reducing the overall throughput (in one case to 0).

Our investigation suggests that there is at least one case when this can happen:

`slick.basic.BasicBackend.DatabaseDef#releaseSession` being called with `discardErrors=fails` may fail to nullify ctx.currentSession.
```scala
    protected[this] final def releaseSession(ctx: Context, discardErrors: Boolean): Unit =
      if(!ctx.isPinned) {
        try ctx.currentSession.close() catch { case NonFatal(ex) if(discardErrors) => }
        ctx.currentSession = null
      }
```

Because of that `slick.basic.BasicBackend.DatabaseDef#runSynchronousDatabaseAction` may skip setting `connectionReleased = true` due to `ctx.priority(continuation) != WithConnection` being `false`.
```scala
…
  releaseSession(ctx, false)
  res
} finally {
  if (!ctx.isPinned && ctx.priority(continuation) != WithConnection) connectionReleased = true
  …
```

This, finally, prevents `afterExecute` in `slick.util.AsyncExecutor` from decrementing `inUseCount`
```scala
(r, queue) match {
  case (pr: PrioritizedRunnable, q: ManagedArrayBlockingQueue[Runnable]) if pr.connectionReleased => q.decreaseInUseCount()
```

**STEPS TO REPRODUCE:**

Sadly, I don't have a well-prepared reproducer. One has to saturate the DB connections with requests and have enough of bad luck to terminate them to trigger the issue.

Synthetically it can be triggered by making a wrapper `java.sql.Connection` that always throws in `close`
```scala
def close(): Unit = throw new SQLException("BOOM!")
```

In our production logs it manifested as
```
java.sql.SQLException: Invalid state, the Connection object is closed.
       at net.sourceforge.jtds.jdbc.JtdsConnection.checkOpen(JtdsConnection.java:1744)
       at net.sourceforge.jtds.jdbc.JtdsConnection.clearWarnings(JtdsConnection.java:2068)
       at com.zaxxer.hikari.pool.ProxyConnection.close(ProxyConnection.java:267)
       at slick.jdbc.JdbcBackend$BaseSession.close(JdbcBackend.scala:508)
       at slick.basic.BasicBackend$DatabaseDef.releaseSession(BasicBackend.scala:258)
       at slick.basic.BasicBackend$DatabaseDef.releaseSession$(BasicBackend.scala:256)
       at slick.jdbc.JdbcBackend$DatabaseDef.releaseSession(JdbcBackend.scala:37)
       at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:280)
       …
```

**EXPECTED RESULT:**

We expect slick to recover from any errors thrown by individual DB connections.

**ACTUAL RESULT:**

Some errors permanently degrade the throughput.

**SETUP:**

In production we use MS SQL Server 2016 SP3 with `net.sourceforge.jtds:jtds:1.3.1` driver. But I think the problem is DB-agnostic.

**POSSIBLE FIX:**

Probably it would be enough to amend `slick.basic.BasicBackend.DatabaseDef#releaseSession` like this, but I may be missing something:
```scala
protected[this] final def releaseSession(ctx: Context, discardErrors: Boolean): Unit =
  if(!ctx.isPinned) {
    val session = ctx.currentSession
    ctx.currentSession = null
    try session.close() catch { case NonFatal(ex) if(discardErrors) => }
  }
```
`!ctx.isPinned` condition also looks suspicious, but perhaps slick guarantees those would be taken care of elsewhere.

**Comment by lenin122** [comment]
Did you checked it in 3.4.0-m1? I had similar issue and it was fixed their

**Comment by sirmax** [comment]
@lenin122 I haven't checked this in production, but as far as I see, `releaseSession` in `3.4.0-M1` can still throw and hold the session, so I doubt it's fixed.

https://github.com/slick/slick/blob/v3.4.0-M1/slick/src/main/scala/slick/basic/BasicBackend.scala#L256-L260

**Comment by nafg** [comment]
Can you open a PR? Even contributing a test would help but Slick is community-maintained so the only way to ensure it's fixed is by fixing it yourself.

**Comment by nafg** [comment]
Relates to https://github.com/slick/slick/discussions/2432

**Comment by nafg** [comment]
@sirmax can you test https://github.com/slick/slick/pull/2620 please?

**Comment by sirmax** [comment]
Hi @nafg! I'm sorry for not replying before.

I can confirm that with locally built `3.5.0-pre.151.4e3d165f` errors in `.close()` no longer make connections permanently stuck. I haven't tested any other slick feature though.

**Comment by nafg** [comment]
@sirmax sorry for the delay. I just rebased it after a related change was merged. Can you test again, after which I am ready to merge it.

**Comment by sirmax** [comment]
Hi 👋 

Tested with locally built `3.5.0-pre.179.ee3b0063` – the fix is working. Haven't tested anything else.
